- name: Setting Controller
  hosts:
    - sv_kst01

  tasks:
#   - name: create db
#     command: "mysql -u{{ DB_USER }} -p{{ DB_PASSWD }} -e 'CREATE DATABASE glance;'"

#   - name: grant db1
#     command: "mysql -u{{ DB_USER }} -p{{ DB_PASSWD }} -e \"GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '{{ DB_PASSWD  }}';\""

#   - name: grant db2
#     command: "mysql -u{{ DB_USER }} -p{{ DB_PASSWD }} -e \"GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '{{ DB_PASSWD  }}';\""
    
#   - name: Create glance user
#     expect:
#       command: openstack --os-auth-url http://controller:5000/v3 user create --domain default --password-prompt glance
#       responses:
#         "User Password": "qwe123"
#         "Repeat User Password": "qwe123"
#     environment:
#       OS_PROJECT_DOMAIN_NAME: Default
#       OS_USER_DOMAIN_NAME: Default
#       OS_PROJECT_NAME: admin
#       OS_USERNAME: admin
#       OS_PASSWORD: "{{ DB_PASSWD }}"
#       OS_IDENTITY_API_VERSION: '3'
#       OS_IMAGE_API_VERSION: '2' 

    - name: Add admin role to glance user
      command: openstack --os-auth-url http://controller:5000/v3 role add --project service --user glance admin
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'        
   
    - name: create glance service 
      command: openstack --os-auth-url http://controller:5000/v3 service create --name glance --description "OpenStack Image" image
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'        
 

    - name: create image service api endpoint1
      command: openstack --os-auth-url http://controller:5000/v3 endpoint create --region RegionOne image public http://controller:9292
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'        

    - name: create image service api endpoint2
      command: openstack --os-auth-url http://controller:5000/v3  endpoint create --region RegionOne  image internal http://controller:9292
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'        
    
    - name: create image service api endpoint3
      command: openstack --os-auth-url http://controller:5000/v3 endpoint create --region RegionOne image admin http://controller:9292
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'        

    - name: install openstack-glance
      yum:
        name: openstack-glance
        state: latest        

    - name: Copy glance configuration file
      copy:
        src: ~/ansible/test-ansible/conf/controller/glance-api.conf
        dest: /etc/glance/glance-api.conf

    - name: Reset image service database
      command: su -s /bin/sh -c "glance-manage db_sync" glance 
    
    - name: enable glance-api-service
      command: systemctl enable openstack-glance-api.service
 
    - name: start glance-api-service
      command: systemctl start openstack-glance-api.service
 


