- name: Setting Controller
  hosts:
    - sv_kst01

  tasks:

    - name: create neutron db
      command: "mysql -u{{ DB_USER }} -p{{ DB_PASSWD }} -e 'CREATE DATABASE neutron;'"
      
    - name: grant db1
      command: "mysql -u{{ DB_USER }} -p{{ DB_PASSWD }} -e \"GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '{{ DB_PASSWD  }}';\""

    - name: grant db2
      command: "mysql -u{{ DB_USER }} -p{{ DB_PASSWD }} -e \"GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '{{ DB_PASSWD  }}';\""
    

    - name: Create neutron user
      expect:
        command: openstack --os-auth-url http://controller:5000/v3 user create --domain default --password-prompt neutron
        responses:
          "User Password": "{{ DB_PASSWD }}"
          "Repeat User Password": "{{ DB_PASSWD }}"
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2' 

    - name: Add admin role to neutron user
      command: openstack --os-auth-url http://controller:5000/v3 role add --project service --user neutron admin
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'        
   
    - name: create neutron service 
      command: openstack --os-auth-url http://controller:5000/v3 service create --name neutron --description "OpenStack Networking" network
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'        
 

    - name: create neutron endpoint1
      command: openstack --os-auth-url http://controller:5000/v3 endpoint create --region RegionOne network public http://controller:9696
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'        

    - name: create neutron endpoint2
      command: openstack --os-auth-url http://controller:5000/v3 endpoint create --region RegionOne network internal http://controller:9696
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'        
    
    - name: create neutron endpoint3
      command: openstack --os-auth-url http://controller:5000/v3 endpoint create --region RegionOne network admin http://controller:9696
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'        

    - name: install openstack-neutron
      yum:
        name: openstack-neutron
        state: latest        

    - name: install openstack-neutron-ml2
      yum:
        name: openstack-neutron-ml2
        state: latest        
   
    - name: openstack-neutron-linuxbridge
      yum:
        name: openstack-neutron-linuxbridge
        state: latest        

    - name: install ebtables
      yum:
        name: ebtables
        state: latest        

    - name: Copy neutron controller configuration file
      copy:
        src: ~/ansible/test-ansible/conf/controller/neutron.conf
        dest: /etc/neutron/neutron.conf

    - name: Copy ml2 configuration file
      copy:
        src: ~/ansible/test-ansible/conf/controller/ml2_conf.ini
        dest: /etc/neutron/plugins/ml2/ml2_conf.ini
     
    - name: Copy linuxbridge_agent configuration file
      copy:
        src: ~/ansible/test-ansible/conf/controller/linuxbridge_agent.ini
        dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini

    - name: Copy l3_agent configuration file
      copy:
        src: ~/ansible/test-ansible/conf/controller/l3_agent.ini
        dest: /etc/neutron/l3_agent.ini

    - name: Copy br_netfilter configuration file
      copy:
        src: ~/ansible/test-ansible/conf/controller/br_netfilter.conf
        dest: /etc/modules-load.d/br_netfilter.conf

    - name: Copy dhcp_agent configuration file
      copy:
        src: ~/ansible/test-ansible/conf/controller/dhcp_agent.ini
        dest: /etc/neutron/dhcp_agent.ini

    - name: Copy metadata_agent configuration file
      copy:
        src: ~/ansible/test-ansible/conf/controller/metadata_agent.ini
        dest: /etc/neutron/metadata_agent.ini

    - name: Create neutron link
      command: ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
  
    - name: Reset database
      command: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron

    - name: Restart Compute API
      command: systemctl restart openstack-nova-api.service
  
    - name: Enable neutron server
      command: systemctl enable neutron-server.service neutron-linuxbridge-agent.service neutron-dhcp-agent.service neutron-metadata-agent.service
   
    - name: Start neutron server
      command: systemctl start neutron-server.service neutron-linuxbridge-agent.service neutron-dhcp-agent.service neutron-metadata-agent.service
 
    - name: Enable neutron l3 
      command: systemctl enable neutron-l3-agent.service
 
    - name: Start neutron l3 
      command: systemctl start neutron-l3-agent.service
 
 

  
