- name: Setting Compute
  hosts:
    - sv_kst01

  tasks:

    - name: Add compute node in controller node
      command: openstack --os-auth-url http://controller:5000/v3 compute service list --service nova-compute
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2'
 
    - name: Add compute node in controller node2
      command: nova --os-auth-url http://controller:5000/v3 hypervisor-list
      environment:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ DB_PASSWD }}"
        OS_AUTH_URL: http://controller:5000/v3
        OS_IDENTITY_API_VERSION: '3'
        OS_IMAGE_API_VERSION: '2' 
 


