---
- name: add_hosts
  hosts: 
    - node04
    - node05
    - node06

  tasks:
    - name: Add hosts file
      blockinfile:
          path: /etc/hosts
          block: |
             192.168.56.111 bu20-04
             192.168.56.112 bu20-05
             192.168.56.113 bu20-06
